import "../styles/globals.css";
import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "../components/shared/Layout";

const inter = Inter({
  name: 'Inter',
  family: 'Inter',
  weight: ['200', '300', '400', '500', '600', '700', '800'],
	subsets: ['latin']
});

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Property - Zaptek</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${inter.variable} font-sans`}>
				<Layout>
					<Component {...pageProps} />
				</Layout>
			</main>
		</>
	);
}

export default MyApp;
