import '../styles/globals.css'
import Head from 'next/head'
import { Inter } from 'next/font/google'
 
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
      <title>Property - Zaptek</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={`${inter.variable}`}>
        <Component {...pageProps} />
      </main>
    </>
  )
  
}

export default MyApp
