import "../styles/globals.css";
import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "../components/shared/Layout";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Property - Zaptek</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<main className={`${inter.variable} font-sans`}>
				<Layout>
					<div className="mt-20">
						<Component {...pageProps} />
					</div>
				</Layout>
			</main>
		</>
	);
}

export default MyApp;
